"""Linear scalarisation utility.

For each (task, method) we report the linear utility
    U(w, f) = w · f_norm
under a preference grid w on the unit simplex, where f_norm is the
min-max-normalised objective vector.

Normalisation
-------------
For each task, per objective j we compute
    lo_j = min over all individuals of *all* methods of f_ij
    hi_j = max over all individuals of *all* methods of f_ij
    f_norm_ij = (f_ij - lo_j) / (hi_j - lo_j)
so every objective lies in [0, 1] before the linear combination.  Using a
shared (lo, hi) across methods keeps cross-method comparisons meaningful.

Method semantics
----------------
* Non-ES methods (RS / HoE / MORLHF / RiC / MOD): the i-th individual was
  trained for the i-th preference in the canonical simplex (verified by spot
  checks against rs row 0, 5, 20).  Utility is therefore
      u_i = w_i · f_i
* ES: a population, not a per-preference checkpoint.  For each preference w
  we pick the best individual from the pool,
      u(w) = max_i  w · f_i

Preference grid
---------------
Generated by the same lexicographic enumeration used during training
(nsgaii_utils.get_simplex_samples).  Steps:
    - Beaver (2 objectives):              step = 0.1  →  11 preferences
    - Assistant / Summary (3 objectives): step = 0.2  →  21 preferences

Outputs
-------
For each task: pretty-printed table with one row per preference and one
column per method, plus the per-method mean utility across the grid.
CSVs are written to plots/utility_linear_<task>.csv.
"""
import os
from itertools import product

import numpy as np

from _mo_data import (
    asst_es, asst_rs, asst_hoe, asst_morl, asst_ric, asst_mod,
    summ_es, summ_rs, summ_hoe, summ_morl, summ_ric, summ_mod,
    bvr_es,  bvr_rs,  bvr_hoe,  bvr_morl,  bvr_ric,  bvr_mod,
)


# ---------------------------------------------------------------------------
# Preference grid (matches nsgaii_utils.get_simplex_samples)
# ---------------------------------------------------------------------------
def simplex_grid(n_objectives: int, step: float) -> np.ndarray:
    n_steps = round(1.0 / step)
    vals    = [round(i * step, 8) for i in range(n_steps + 1)]
    pts     = [list(c) for c in product(vals, repeat=n_objectives)
               if abs(sum(c) - 1.0) < 1e-6]
    return np.array(pts)


# ---------------------------------------------------------------------------
# Normalisation
# ---------------------------------------------------------------------------
def minmax_bounds(arrays):
    """Return (lo, hi) per objective, pooling every method's individuals."""
    stacked = np.vstack(arrays)
    lo = stacked.min(axis=0)
    hi = stacked.max(axis=0)
    return lo, hi


def normalise(arr: np.ndarray, lo: np.ndarray, hi: np.ndarray) -> np.ndarray:
    span = np.where(hi > lo, hi - lo, 1.0)   # guard against degenerate objectives
    return (arr - lo) / span


# ---------------------------------------------------------------------------
# Utility computation
# ---------------------------------------------------------------------------
def linear_utility(arr: np.ndarray, prefs: np.ndarray, is_es: bool) -> np.ndarray:
    """Return per-preference linear utility, shape (P,).

    arr   : (N, k) objective values for one method.
    prefs : (P, k) preference grid.
    is_es : True  → u(w) = max_i  w · f_i        (argmax over pool)
            False → u(w_i) = w_i · f_i          (row i ↔ preference i)
    """
    if is_es:
        # (P, N) = (P, k) @ (k, N)  →  max over N
        return (prefs @ arr.T).max(axis=1)
    if len(arr) != len(prefs):
        raise ValueError(
            f'non-ES method has {len(arr)} rows but preference grid has '
            f'{len(prefs)} entries — row/preference order cannot align.')
    return (prefs * arr).sum(axis=1)


# ---------------------------------------------------------------------------
# Tasks
# ---------------------------------------------------------------------------
TASKS = [
    ('assistant', 3, 0.2, [
        ('ES',     asst_es),
        ('RS',     asst_rs),
        ('HoE',    asst_hoe),
        ('MORLHF', asst_morl),
        ('RiC',    asst_ric),
        ('MOD',    asst_mod),
    ]),
    ('summary',   3, 0.2, [
        ('ES',     summ_es),
        ('RS',     summ_rs),
        ('HoE',    summ_hoe),
        ('MORLHF', summ_morl),
        ('RiC',    summ_ric),
        ('MOD',    summ_mod),
    ]),
    ('beaver',    2, 0.1, [
        ('ES',     bvr_es),
        ('RS',     bvr_rs),
        ('HoE',    bvr_hoe),
        ('MORLHF', bvr_morl),
        ('RiC',    bvr_ric),
        ('MOD',    bvr_mod),
    ]),
]


def _fmt_pref(w):
    return '(' + ', '.join(f'{v:.1f}' for v in w) + ')'


def run(save_csv: bool = True):
    if save_csv:
        os.makedirs('plots', exist_ok=True)

    for task, n_obj, step, methods in TASKS:
        prefs = simplex_grid(n_obj, step)

        # ---- shared min-max bounds across every method's pool ----
        lo, hi = minmax_bounds([arr for _, arr in methods])
        normed = [(name, normalise(arr, lo, hi)) for name, arr in methods]

        results = {}
        for name, arr in normed:
            results[name] = linear_utility(arr, prefs, is_es=(name == 'ES'))

        # ---- pretty table ----
        print(f'\n=== Linear utility — {task} '
              f'(n_obj={n_obj}, step={step}, P={len(prefs)}) ===')
        print(f'  lo = {np.array2string(lo, precision=4)}'
              f'   hi = {np.array2string(hi, precision=4)}')
        header = f'{"w":>{n_obj * 6 + 2}s}  ' + '  '.join(
            f'{n:>8s}' for n, _ in methods)
        print(header)
        print('-' * len(header))
        for i, w in enumerate(prefs):
            row_vals = '  '.join(f'{results[n][i]:>8.4f}' for n, _ in methods)
            print(f'{_fmt_pref(w):>{n_obj * 6 + 2}s}  {row_vals}')

        # ---- summary statistics ----
        print(f'{"mean":>{n_obj * 6 + 2}s}  ' + '  '.join(
            f'{results[n].mean():>8.4f}' for n, _ in methods))
        winners = np.array([results[n] for n, _ in methods]).argmax(axis=0)
        win_counts = {n: int((winners == i).sum())
                      for i, (n, _) in enumerate(methods)}
        print(f'{"#wins":>{n_obj * 6 + 2}s}  ' + '  '.join(
            f'{win_counts[n]:>8d}' for n, _ in methods))

        # ---- CSV ----
        if save_csv:
            path = f'plots/utility_linear_{task}.csv'
            with open(path, 'w') as f:
                f.write('preference,' + ','.join(n for n, _ in methods) + '\n')
                for i, w in enumerate(prefs):
                    f.write(_fmt_pref(w).replace(',', ';') + ',' +
                            ','.join(f'{results[n][i]:.6f}'
                                     for n, _ in methods) + '\n')
            print(f'  → saved {path}')


if __name__ == '__main__':
    run()
